# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2017 Scouting Collection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2017 Scouting Collection
  
  pod "QRCode"
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
  pod 'Alamofire', '~> 4.0'
  
  target '2017 Scouting CollectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '2017 Scouting CollectionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
